### PR TITLE
Add a page number indication for examples

### LINKED ISSUE #8: There isn't indicator of how many pages one command's documentation has.
When a command is typed, its documentation shows up in the bottom of the screen. `Ctrl+N` and `Ctrl+Y` are used to scroll the documentation. However there isn't any indicator of how many pages of documentation left.

```
az vm>> create                            
                      
                   
                   




-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Create an Azure Virtual Machine.                                                         *
                                                                                         *                                                                                         
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[1] Create a simple Ubuntu VM with automatic SSH authentication.                          
az vm create -n MyVm -g MyResourceGroup --image UbuntuLTS                                                                                                                          
                                                                                                                                                                         
[2] Create a simple Windows Server VM with a private IP address.
az vm create -n MyVm -g MyResourceGroup                  
 --public-ip-address "" --image Win2012R2Datacenter                                                                                                       
                                                                                                                                                                                   
[3] Create a VM from a custom managed image (see `az image create` for generation information).
az vm create -g MyResourceGroup -n MyVm --image MyImage                                   
                                                                                          
[4] Create a VM by attaching to a specialized managed operating system disk.              
az vm create -g MyResourceGroup -n MyVm --attach-os-disk MyOsDisk --os-type linux                                                                                                 
                                                                                                                                                                                   
[5] Create an Ubuntu Linux VM and provide a cloud-init script (https://docs.microsoft.com/azure/virtual-machines/virtual-machines-linux-using-cloud-init).
az vm create -g MyResourceGroup -n MyVm --image debian --custom_data MyCloudInitScript.yml
                                      
[6] Create a Linux VM with SSH key authentication, add a public DNS entry, and then add it to an existing virtual network and availability set.
az vm create -n MyVm -g MyResourceGroup --image <linux image from 'az vm image list'> --vnet-name MyVnet --subnet subnet1 --availability-set MyAvailabilitySet --public-i          
p-address-dns-name MyUniqueDnsName --ssh-key-value "<ssh-rsa-key, key-file-path or not specified for default-key-path>"
                                                          
[7] Create a simple Ubuntu Linux VM with a public IP address, DNS entry, 2 data disk(10GB, 20GB), and then generate ssh key pairs under ~/.ssh.
                                                                                                                                                                                   
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
?[path]            : query previous command using jmespath syntax
[cmd] :: [num]     : do a step by step tutorial of example
#[cmd]             : use commands outside the application
^^                 : undefault a scope                        
$                  : get the exit code of the previous command
%%                 : default a scope              
Crtl+N             : Scroll down the documentation                                                                                                                                
Crtl+Y             : Scroll up the documentation
```

### PR DESCRIPTION
**Pull request by oakeyc**
fixes #8

### CODE REVIEW

**Comment by derekbekoe** [comment]
@oakeyc What does this look like in the shell?
Also, this change includes the version no. changes. Can you make those a separate?

**Comment by oakeyc** [comment]
screen shot 2017-04-14 at 3 44 25 pm
screen shot 2017-04-14 at 3 44 10 pm

I think the version numbers were already merged in another PR

**Comment by derekbekoe** [comment]
Thanks for the pics.
It doesn't look like it's been merged in since it's not here. https://github.com/Azure/azure-cli-shell/blob/master/HISTORY.rst

**Comment by oakeyc** [comment]
changes made

**Review by derekbekoe — APPROVED** [review]

**Pull request merged**
